config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
 
  resources :books
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
	validates :title, presence: true,
                    length: { minimum: 5 }  
  mount_uploader :attachment, AttachmentUploader  
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController	
	before_action :find_user, only: [:show,:edit,:update,:destroy]
	before_action :authenticate_user!
	
	
	def index
   	     
   	   if params[:search]
   	      @books = Book.all.includes(:user).where("lower(title) LIKE ? or lower(text) LIKE ? ", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%")  	   
   	   else
   		  @books = Book.all.includes(:user) 
   		end
   		respond_to do |format|
          format.html  # index.html.erb
          format.js
        end
    end
	
	def show
	    
  	end
	
	def new
		@book = Book.new
	end
  	
  	def edit
	end
  	
  	def create
  		@book = Book.new(book_params)
  		@book.attachment = params[:book][:attachment]
  		@book.user_id = current_user.id
   		if @book.save
   			#BookMailer.registration_confirmation(current_user).deliver
	    	redirect_to @book
	   	else
	    	render 'new'
	   	end
  	end
  	
  	def update
	    if @book.update(book_params)
	      redirect_to @book
	    else
	      render 'edit'
	    end
  	end
 
	def destroy
		@book.destroy
		redirect_to books_path	
	end

	def find_user
		@book= Book.find(params[:id])
	end
	private
	def book_params
		params.require(:book).permit(:title, :text, :attachment)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_books.html.erb
<%if @books.present?%>
  <table>
    <tr>
      <br>
      <th>Title</th>
      <th>Text</th>
      <th>Username</th>
      <th colspan="2"></th>
    </tr>    
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.text %></td>
        <td><%= book.user.try(:username) %></td>
        <td><%= link_to 'Show', book_path(book) %></td> 
        <% if book.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Destroy', book_path(book),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
                <% end %>
         <% end %>       
      </tr>
    <% end %>
  </table>
<%end%>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>
 
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :attachment  %><br>
    <%= form.file_field :attachment %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/books/edit.html.erb
<h1>Edit book</h1>
 <%= render 'form' %>
 <%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<body>
  <br>
  <div class="id">
    <h1>Listing books</h1>
    <br>
      <%= link_to 'New book', new_book_path %>
      <%= form_tag @book_path, :method => 'get' ,remote:true do %>
    <p>  
    <br>
      <%= text_field_tag :search, params[:search], id: "search" %>
      <%= submit_tag "Search",id: "search_btn" %>
  </div>
  <% end %>
<br>
<br>
   <div class ="books">
      <%= render 'books' %>
   </div>
<br>
<br>
<% if user_signed_in? %>
  <li>
    <%= button_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
    <%= link_to('Login', new_user_session_path)  %>  
  </li>

<script type="text/javascript" src="somescript.js">
   $("#search_btn").click(function(evt){
     evt.preventDefault();
      $.ajax({
      type: "get",
      url: "books_path",
      data: $(this).serialize(),
      success: function(response) {
     }
   });
})
</script>
<% end %>
</body>

app/views/books/index.js.erb
$('.books').html("<%= escape_javascript render(:partial => 'books', :locals => { :c => @books }) %>");

app/views/books/new.html.erb
<h1>New book</h1>
 <%= render 'form' %>
 <%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
   <strong>Title:</strong>
   <%= @book.title %>
</p>
<p>
   <strong>Text:</strong>
   <%= @book.text %>
</p>
  <%= @book.created_at %>
  <%= @book.user_id %>
  <%=link_to "show pdf",@book.attachment.url %>
  <%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My login', controller: 'books' %>